POST http://localhost:8080/add
Content-Type: application/json

{
    "id": "0001",
    "name": "name",
    "data": ["a", "b"]

}

###
POST http://localhost:8080/add
Content-Type: application/json

{
  "id": "0001",
  "name": "name1",
  "data": ["c", "d"]

}

###

POST http://localhost:8080/remove
Content-Type: application/json

{
"id": "0001",
"name": "name1",
"data": ["c", "d"]

}

###

GET http://localhost:8080/retrieve/0001
Content-Type: application/json
